
<field:xm itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xm>

<field:xb itemname="系别" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xb>

<field:xmm itemname="项目" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xmm>

<field:dh itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dh>
