<?php
$z[0]=Array("field","",332,351);
$z[0][4]['name']="title";
$z[1]=Array("global","",352,378);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field"," if(@me<>'' )@me = ''.@me.'';",422,513);
$z[2][4]['name']="description";
$z[2][4]['runphp']="yes";
$z[3]=Array("field","",550,572);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1183,1220);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("type","[field:typename/]",1287,1327);
$z[6]=Array("field","",1345,1364);
$z[6][4]['name']="title";
$z[7]=Array("field","",1401,1419);
$z[7][4]['name']="body";
$z[8]=Array("field","",1468,1520);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("include","",1591,1628);
$z[9][4]['filename']="foot_m.htm";

?>