<?php
$z[0]=Array("field","",26,49);
$z[0][4]['name']="id";
$z[1]=Array("field","",51,80);
$z[1][4]['name']="typename";
$z[2]=Array("field","",219,242);
$z[2][4]['name']="id";
$z[3]=Array("field","",244,273);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n        ",287,425);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>