<?php
$z[0]=Array("field","",13,36);
$z[0][4]['name']="id";
$z[1]=Array("field","",38,67);
$z[1][4]['name']="typename";
$z[2]=Array("field","",193,216);
$z[2][4]['name']="id";
$z[3]=Array("field","",218,247);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n        ",261,399);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>