<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",304,325);
$z[2][4]['name']="pagexx";
$z[3]=Array("field","",372,430);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",467,496);
$z[4][4]['name']="keywords";
$z[5]=Array("include","",643,678);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",766,795);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n    <li><a href=\"[field:xiazai/]\">[field:title/]\r\n      <p><img src=\"/images/download.jpg\" width=\"100\" height=\"40\" /></p>\r\n    </a></li>\r\n ",871,1049);
$z[7][4]['pagesize']="10";
$z[8]=Array("include","",1070,1106);
$z[8][4]['filename']="right.htm";
$z[9]=Array("include","",1138,1173);
$z[9][4]['filename']="foot.htm";

?>