<?php
$z[0]=Array("channelartlist","\r\n        <li><a href=\"list.php?tid={dede:field name='id'/}\">{dede:field name='typename'/}</a>\r\n        <ul class=\"dl-submenu\">\r\n        <li class=\"dl-back\"><a href=\"#\">返回上一级</a></li>\r\n        <li><a href=\"list.php?tid={dede:field name='id'/}\">{dede:field name='typename'/}</a>\r\n        {dede:channel type='son' noself='yes'}\r\n        <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n        {/dede:channel}\r\n        </ul>\r\n        </li>\r\n      ",222,756);
$z[0][4]['typeid']="top";
$z[0][4]['row']="16";

?>