<?php
$z[0]=Array("mytime","\r\n@me=date(\"Y年 m月 d日\");\r\n\$weekarray=array(\"日\",\"一\",\"二\",\"三\",\"四\",\"五\",\"六\");  \r\n@me = date(\"Y年 m月 d日\").\"  星期\".\$weekarray[date(\"w\")]; \r\n",154,354);
$z[0][4]['runphp']="yes";
$z[1]=Array("type"," [field:typelink /]",835,886);
$z[1][4]['typeid']="1";
$z[2]=Array("channel","  <LI><A href=\"[field:typeurl/]\">[field:typename/]</A> </LI> ",926,1047);
$z[2][4]['type']="son";
$z[2][4]['typeid']="1";
$z[2][4]['row']="10";
$z[3]=Array("channelartlist","\r\n<li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n",1077,1249);
$z[3][4]['row']="10";
$z[3][4]['typeid']="5,6,7,8,9,10,11,12,13,14";

?>