<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",304,325);
$z[2][4]['name']="pagexx";
$z[3]=Array("field","",372,430);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",467,496);
$z[4][4]['name']="keywords";
$z[5]=Array("include","",651,686);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",774,803);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n      <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"210\" height=\"290\" />\r\n        <p>[field:title/]</p>\r\n      </a></li>\r\n\r\n",882,1062);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",1139,1205);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",1243,1279);
$z[9][4]['filename']="right.htm";
$z[10]=Array("include","",1311,1346);
$z[10][4]['filename']="foot.htm";

?>