<?php
$z[0]=Array("field","",332,351);
$z[0][4]['name']="title";
$z[1]=Array("global","",352,378);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",382,403);
$z[2][4]['name']="pagexx";
$z[3]=Array("field","",450,508);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",545,574);
$z[4][4]['name']="keywords";
$z[5]=Array("include","",1185,1222);
$z[5][4]['filename']="head_m.htm";
$z[6]=Array("type","[field:typename/]",1283,1323);
$z[7]=Array("list","\r\n    <li><a href=\"view.php?aid=[field:id/]\">[field:title/]</a></li>\r\n",1366,1473);
$z[7][4]['pagesize']="10";
$z[8]=Array("pagelist","",1568,1634);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",1709,1746);
$z[9][4]['filename']="foot_m.htm";

?>