<?php
$z[0]=Array("field","",37,59);
$z[0][4]['name']="typename";
$z[1]=Array("channel","  <LI><A href=\"[field:typeurl/]\">[field:typename/]</A> </LI> ",86,196);
$z[1][4]['type']="son";
$z[1][4]['row']="10";
$z[2]=Array("arclist","\r\n     <li><a href=\"[field:arcurl/]\"><span>[[field:pubdate function=MyDate('m-d',@me)/]]</span>[field:title/]</a></li>\r\n",409,578);
$z[2][4]['row']="5";
$z[2][4]['typeid']="16";

?>