<?php
$z[0]=Array("mytime","\r\n@me=date(\"Y年 m月 d日\");\r\n\$weekarray=array(\"日\",\"一\",\"二\",\"三\",\"四\",\"五\",\"六\");  \r\n@me = date(\"Y年 m月 d日\").\"  星期\".\$weekarray[date(\"w\")]; \r\n",154,354);
$z[0][4]['runphp']="yes";
$z[1]=Array("arclist","\r\n					<li class='touchslider-item'>\r\n						<a href='javascript:onSWT();'><img src='[field:litpic/]'  height=\"560\"  /></a>\r\n					</li>\r\n		",1131,1318);
$z[1][4]['row']="3";
$z[1][4]['typeid']="23";
$z[2]=Array("type"," [field:typelink /]",1839,1890);
$z[2][4]['typeid']="1";
$z[3]=Array("channel","  <LI><A href=\"[field:typeurl/]\">[field:typename/]</A> </LI> ",1930,2051);
$z[3][4]['type']="son";
$z[3][4]['typeid']="1";
$z[3][4]['row']="10";
$z[4]=Array("channelartlist","\r\n<li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n",2081,2253);
$z[4][4]['row']="10";
$z[4][4]['typeid']="5,6,7,8,9,10,11,12,13,14";

?>